namespace AkaEnum
{
    public enum RewardType
    {
        None = 0,
        EnergyBox01 = 1,
        SmallUnitBox = 2,
        BigUnitBox = 3,
        SmallSkillBox = 4,
        BigSkillBox = 5,
        BonusEnergy = 6,
        Skin = 7,
        Unit = 8,
        UnitPiece = 9,
        Skill = 10,
        SkillPiece = 11,
        WeaponBox = 12,
        WeaponToken = 13,
        GalaxyDollar01 = 14,
        GalaxyDollar02 = 15,
        GalaxyDollar03 = 16,
        GalaxyDollar04 = 17,
        RareMetal01 = 18,
        RareMetal02 = 19,
        RareMetal03 = 20,
        RareMetal04 = 21,
        Emoticon = 22,
        UnitProfile = 23,
        UnitSpecialPiece = 24,
        SquareObjectStartTicket = 25,
        WeaponPiece = 26,
        SquareObjectBox = 27,
        SeasonPass = 28,
        SeasonBox = 29,
        EnergyBox02 = 30,
        EnergyBox03 = 31,
        EnergyBox04 = 32,
        EventUnitBox = 33,
        SquareObject = 101,
        UnlockQuest = 102,
        DynamicQuest = 103,
    }
}
