version: "3.7" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  mysql: # 서비스 명
    image: mysql:5.7 # 사용할 이미지
    restart: always
    command: --lower_case_table_names=1
    container_name: mysql-dev # 컨테이너 이름 설정
    ports:
      - "3307:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      #- MYSQL_DATABASE=account
      - MYSQL_ROOT_PASSWORD=fnfntdh31!#!  # MYSQL 패스워드 설정 옵션
      - TZ=Asia/Seoul

    command: # 명령어 실행
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      #- /Users/Shared/data/mysql-test:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
      - ./../../game-db-data:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)

  flyway-account:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas=account -user=root -password=fnfntdh31!#! -connectRetries=60 migrate
    volumes:
      - ./../DbMigration/Account:/flyway/sql
    depends_on:
      - mysql

  flyway-knightrun:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas=knightrun -user=root -password=fnfntdh31!#! -connectRetries=60 migrate
    volumes:
      - ./../DbMigration/KnightRun:/flyway/sql
    depends_on:
      - mysql
  
  redis:
    image: redis:alpine
    container_name: redisalpine
    hostname: redisalpine
    command: redis-server --port 6379
    ports:
      - 16379:6379