CREATE TABLE `_mail_public` (
	`mailId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`startDateTime` DATETIME NULL DEFAULT NULL,
	`endDateTime` DATETIME NULL DEFAULT NULL,
	`mailIcon` INT(11) NULL DEFAULT NULL,
	`productId` INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`mailId`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
