-- Script generated by MySQL Compare 1.0.1.4 on 2018-08-08 오후 1:36:17

ALTER TABLE `knightrun_gmtool`.`game_table`
  MODIFY COLUMN `comment` text ;

ALTER TABLE `knightrun_gmtool`.`server_list`
  ADD COLUMN `isRunning` bit(1) NOT NULL DEFAULT b'0';

DROP PROCEDURE `knightrun_gmtool`.`p_transferLatestGameTable`;

DELIMITER |
CREATE PROCEDURE `p_transferLatestGameTable`(
	IN `$from_runMode` VARCHAR(10),
	IN `$to_runMode` VARCHAR(10),
	IN `$comment` TINYTEXT

)
BEGIN
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		
  		IF @sqlstate = '45000' THEN
 			SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
 		ELSE
 			SIGNAL SQLSTATE '46000' SET MYSQL_ERRNO = 200, MESSAGE_TEXT = @text;
  		END IF;
  	END;

	START TRANSACTION;
		SELECT @count := COUNT(*) FROM game_table WHERE runMode = $to_runMode;
		IF @count = 0 THEN
			INSERT INTO game_table(tableType, url, runMode, comment, createDate)
			SELECT tableType, max(url) as url, $to_runMode as runMode, $comment as comment, CURRENT_TIMESTAMP() as createDate
			FROM game_table WHERE version > 0 and runMode = $from_runMode GROUP BY tableType;
			
		ELSE 
			INSERT INTO game_table(tableType, url, runMode, comment, createDate) 
			SELECT from_runMode.tableType as tableType, from_runMode.url as url, $to_runMode as runMode, $comment as comment, CURRENT_TIME() as createDate FROM (
				SELECT tableType, max(version) as version, max(url) as url, runMode FROM game_table WHERE runMode = $from_runMode GROUP BY tableType
			) from_runMode INNER JOIN (
				SELECT tableType, max(version) as version, max(url) as url, runMode FROM game_table WHERE runMode = $to_runMode GROUP BY tableType
			) to_runMode 
			ON from_runMode.tableType = to_runMode.tableType and from_runMode.version > to_runMode.version;
		END IF;
	COMMIT;
END|
DELIMITER ;

DROP PROCEDURE `knightrun_gmtool`.`p_updateGameTableToServer`;

DELIMITER |
CREATE PROCEDURE `p_updateGameTableToServer`(
	IN `$hostName` VARCHAR(50),
	IN `$ip` VARCHAR(30),
	IN `$tableVersion` BIGINT,
	IN `$runMode` VARCHAR(10),
	IN `$serverName` VARCHAR(30),
	IN `$isRunning` BIT,
	IN `$updateTime` TIMESTAMP





)
BEGIN
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		
  		IF @sqlstate = '45000' THEN
 			SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
 		ELSE
 			SIGNAL SQLSTATE '46000' SET MYSQL_ERRNO = 200, MESSAGE_TEXT = @text;
  		END IF;
  	END;
  	
  	START TRANSACTION;
  		INSERT INTO server_list(ip, hostName, tableVersion, runMode, serverName, isRunning, updateTime) VALUES($ip, $hostName, $tableVersion, $runMode, $serverName, $isRunning, $updateTime)
  		ON DUPLICATE KEY UPDATE tableVersion = $tableVersion, isRunning = $isRunning, updateTime = $updateTime;
  	COMMIT;
END|
DELIMITER ;


