-- Script generated by MySQL Compare 1.0.1.4 on 2018-11-16 오후 3:07:18

ALTER TABLE `knightrun_gmtool`.`game_table`
  MODIFY COLUMN `createDate` timestamp NOT NULL DEFAULT current_timestamp();

DROP PROCEDURE `knightrun_gmtool`.`p_getFileBetweenVersion`;

DELIMITER |
CREATE PROCEDURE `p_getFileBetweenVersion`(
	IN `$fileType` VARCHAR(15),
	IN `$fromVersion` BIGINT,
	IN `$toVersion` BIGINT,
	IN `$runMode` VARCHAR(10)















)
BEGIN
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		IF @sqlstate = '45000' THEN
 			SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
 		ELSE
 			SIGNAL SQLSTATE '46000' SET MYSQL_ERRNO = 200, MESSAGE_TEXT = @text;
  		END IF;
  	END;

	IF $fileType = 'Table' THEN
		SELECT originTable.version, originTable.name, originTable.url, originTable.runMode FROM (
			SELECT name, max(version) AS version FROM game_table WHERE version > $fromVersion and version <= $toVersion and runMode = $runMode GROUP BY name
		) lastestTable INNER JOIN game_table AS originTable ON lastestTable.name = originTable.name and lastestTable.version = originTable.version
		ORDER BY originTable.version ASC;
	
	ELSEIF $fileType = 'AssetBundle' THEN
		SELECT originTable.version, originTable.name, originTable.url, originTable.runMode FROM (
			SELECT name, max(version) AS version FROM asset_bundle WHERE version > $fromVersion and version <= $toVersion and runMode = $runMode GROUP BY name
		) lastestTable INNER JOIN asset_bundle AS originTable ON lastestTable.name = originTable.name and lastestTable.version = originTable.version
		ORDER BY originTable.version ASC;
	END IF;
END|
DELIMITER ;

DROP PROCEDURE `knightrun_gmtool`.`p_getFileLatestVersion`;

DELIMITER |
CREATE PROCEDURE `p_getFileLatestVersion`(
	IN `$fileType` VARCHAR(15),
	IN `$version` BIGINT,
	IN `$runMode` VARCHAR(10)





























)
BEGIN
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		
  		IF @sqlstate = '45000' THEN
 			SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
 		ELSE
 			SIGNAL SQLSTATE '46000' SET MYSQL_ERRNO = 200, MESSAGE_TEXT = @text;
  		END IF;
  	END;

	IF $fileType = 'Table' THEN
		SELECT originTable.version, originTable.name, originTable.url, originTable.runMode FROM (
			SELECT name, max(version) AS version FROM game_table WHERE version > $version and runMode = $runMode GROUP BY name
		) lastestTable INNER JOIN game_table AS originTable ON lastestTable.name = originTable.name and lastestTable.version = originTable.version
		ORDER BY originTable.version ASC;
	
	ELSEIF $fileType = 'AssetBundle' THEN
		SELECT originTable.version, originTable.name, originTable.url, originTable.runMode FROM (
			SELECT name, max(version) AS version FROM asset_bundle WHERE version > $version and runMode = $runMode GROUP BY name
		) lastestTable INNER JOIN asset_bundle AS originTable ON lastestTable.name = originTable.name and lastestTable.version = originTable.version
		ORDER BY originTable.version ASC;
	END IF;
END|
DELIMITER ;

DROP PROCEDURE `knightrun_gmtool`.`p_getFileWithinVersion`;

DELIMITER |
CREATE PROCEDURE `p_getFileWithinVersion`(
	IN `$fileType` VARCHAR(15),
	IN `$version` BIGINT,
	IN `$runMode` VARCHAR(10)
























)
BEGIN
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		IF @sqlstate = '45000' THEN
 			SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
 		ELSE
 			SIGNAL SQLSTATE '46000' SET MYSQL_ERRNO = 200, MESSAGE_TEXT = @text;
  		END IF;
  	END;

	IF $fileType = 'Table' THEN
		SELECT originTable.version, originTable.name, originTable.url, originTable.runMode FROM (
			SELECT name, max(version) AS version FROM game_table WHERE version <= $version and runMode = $runMode GROUP BY name
		) lastestTable INNER JOIN game_table AS originTable ON lastestTable.name = originTable.name and lastestTable.version = originTable.version
		ORDER BY originTable.version ASC;
		
	ELSEIF $fileType = 'AssetBundle' THEN
		SELECT originTable.version, originTable.name, originTable.url, originTable.runMode FROM (
			SELECT name, max(version) AS version FROM asset_bundle WHERE version <= $version and runMode = $runMode GROUP BY name
		) lastestTable INNER JOIN asset_bundle AS originTable ON lastestTable.name = originTable.name and lastestTable.version = originTable.version
		ORDER BY originTable.version ASC;
	END IF;
END|
DELIMITER ;

DELIMITER |
CREATE PROCEDURE `p_transferLatestFile`(
	IN `$fileType` VARCHAR(15),
	IN `$from_runMode` VARCHAR(10),
	IN `$to_runMode` VARCHAR(10)


















,
	IN `$comment` TINYTEXT




)
BEGIN
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		
  		IF @sqlstate = '45000' THEN
 			SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
 		ELSE
 			SIGNAL SQLSTATE '46000' SET MYSQL_ERRNO = 200, MESSAGE_TEXT = @text;
  		END IF;
  	END;

	START TRANSACTION;
		IF $fileType = 'Table' THEN
			SELECT @count := COUNT(*) FROM game_table WHERE runMode = $to_runMode;
			IF @count = 0 THEN
				INSERT INTO game_table(name, url, runMode, comment, createDate)
				SELECT name, max(url) as url, $to_runMode as runMode, $comment as comment, CURRENT_TIMESTAMP() as createDate
				FROM game_table WHERE version > 0 and runMode = $from_runMode GROUP BY name;
				
			ELSE 
				INSERT INTO game_table(tableType, url, runMode, comment, createDate) 
				SELECT from_runMode.name as name, from_runMode.url as url, $to_runMode as runMode, $comment as comment, CURRENT_TIME() as createDate FROM (
					SELECT name, max(version) as version, max(url) as url, runMode FROM game_table WHERE runMode = $from_runMode GROUP BY name
				) from_runMode INNER JOIN (
					SELECT name, max(version) as version, max(url) as url, runMode FROM game_table WHERE runMode = $to_runMode GROUP BY name
				) to_runMode 
				ON from_runMode.name = to_runMode.name and from_runMode.version > to_runMode.version;
			END IF;
			
		ELSEIF $fileType = 'AssetBundle' THEN
			SELECT @count := COUNT(*) FROM asset_bundle WHERE runMode = $to_runMode;
			IF @count = 0 THEN
				INSERT INTO asset_bundle(name, url, runMode, comment, createDate)
				SELECT name, max(url) as url, $to_runMode as runMode, $comment as comment, CURRENT_TIMESTAMP() as createDate
				FROM asset_bundle WHERE version > 0 and runMode = $from_runMode GROUP BY name;
				
			ELSE 
				INSERT INTO asset_bundle(tableType, url, runMode, comment, createDate) 
				SELECT from_runMode.name as name, from_runMode.url as url, $to_runMode as runMode, $comment as comment, CURRENT_TIME() as createDate FROM (
					SELECT name, max(version) as version, max(url) as url, runMode FROM asset_bundle WHERE runMode = $from_runMode GROUP BY name
				) from_runMode INNER JOIN (
					SELECT name, max(version) as version, max(url) as url, runMode FROM asset_bundle WHERE runMode = $to_runMode GROUP BY name
				) to_runMode 
				ON from_runMode.name = to_runMode.name and from_runMode.version > to_runMode.version;
			END IF;
		END IF;
	COMMIT;
END|
DELIMITER ;
