-- Script generated by MySQL Compare 1.0.1.4 on 2018-12-04 오후 4:01:49

ALTER TABLE `accounts`
  ADD COLUMN `lastLoginDate` timestamp NOT NULL DEFAULT current_timestamp();

ALTER TABLE `decks`
  ADD COLUMN `deckName` varchar(8) NOT NULL DEFAULT '';

DROP PROCEDURE `p_setDeck`;

DELIMITER $$
CREATE PROCEDURE `p_setDeck`(
	IN `$userId` INT,
	IN `$modeType` TINYINT,
	IN `$deckType` TINYINT,
	IN `$deckNum` TINYINT,
	IN `$orderNum` TINYINT,
	IN `$deckName` VARCHAR(8),
	IN `$classId` INT

)
BEGIN  
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION	  
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		
		SET @text = CONCAT(@sqlstate, "|", @text);
		SIGNAL SQLSTATE '02000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
  	END;
  	
  	START TRANSACTION;
	  	
	INSERT INTO decks(userId, modeType, deckType, deckNum, orderNum, deckName, classId) 
	VALUES($userId, $modeType, $deckType, $deckNum, $orderNum, $deckName, $classId)
	ON DUPLICATE KEY UPDATE classId = $classId;
	
	COMMIT;
END$$
DELIMITER ;