-- Script generated by MySQL Compare 1.0.1.4 on 2018-12-05 오후 5:06:47

ALTER TABLE `decks` DROP INDEX `UX_decks_userId_modeType_deckNum_deckType_orderNum`;

ALTER TABLE `decks`
  MODIFY COLUMN `modeType` tinyint(3) unsigned NOT NULL DEFAULT 0
  , CHANGE COLUMN `deckType` `slotType` tinyint(3) unsigned NOT NULL DEFAULT 0;

ALTER TABLE `decks` ADD UNIQUE KEY `UX_decks_userId_modeType_deckNum_slotType_orderNum`(`userId`,`modeType`,`deckNum`,`slotType`,`orderNum`);

ALTER TABLE `ranks`
  MODIFY COLUMN `rankType` tinyint(3) unsigned NOT NULL
  , MODIFY COLUMN `rankPoint` int(10) NOT NULL DEFAULT '0';

DROP PROCEDURE `p_setDeck`;

DELIMITER $$
CREATE PROCEDURE `p_setDeck`(
	IN `$userId` INT,
	IN `$modeType` TINYINT,
	IN `$slotType` TINYINT,
	IN `$deckNum` TINYINT,
	IN `$orderNum` TINYINT,
	IN `$deckName` VARCHAR(8),
	IN `$classId` INT

)
BEGIN  
  	DECLARE EXIT HANDLER FOR SQLEXCEPTION	  
  	BEGIN
  		ROLLBACK;
  		
  		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT; 
  		
		SET @text = CONCAT(@sqlstate, "|", @text);
		SIGNAL SQLSTATE '02000' SET MYSQL_ERRNO = @errno, MESSAGE_TEXT = @text;
  	END;
  	
  	START TRANSACTION;
	  	
	INSERT INTO decks(userId, modeType, slotType, deckNum, orderNum, deckName, classId) 
	VALUES($userId, $modeType, $slotType, $deckNum, $orderNum, $deckName, $classId)
	ON DUPLICATE KEY UPDATE classId = $classId, deckName = $deckName;
	
	COMMIT;
END$$
DELIMITER ;
